from __future__ import annotations

import argparse
import re
import subprocess
import tempfile
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_BREAK, WD_TAB_ALIGNMENT, WD_TAB_LEADER
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.opc.constants import RELATIONSHIP_TYPE as RT
from docx.shared import Inches, Pt, RGBColor
from docx.table import Table
from docx.text.paragraph import Paragraph
from docx.text.run import Run


ROOT = Path(__file__).resolve().parents[1]
OUTPUTS = ROOT / "Document" / "outputs"
SOFFICE = Path(r"C:\Program Files\LibreOffice\program\soffice.com")

TARGETS = [
    OUTPUTS / "final-report.docx",
    OUTPUTS / "final-report-gpt55-comparison.docx",
]

HEADING_STYLE_SIZES = {
    "Heading 1": 16,
    "Heading 2": 14,
    "Heading 3": 12,
}

EXAMPLE_LABELS = {
    "Example:",
    "Example: Security Enhancement",
    "Example: Performance Optimization",
    "Security Enhancement:",
    "Performance Optimization:",
}
EXAMPLE_DETAIL_PREFIXES = (
    "Financial Accounting API:",
    "The API features role-based access control",
    "Baseline Issue:",
    "ChatGPT Recommendation:",
    "Example Adjustment:",
    "Security: Run ZAP",
    "Performance: Run JMeter",
)

TABLE_CAPTION_TITLES = {
    ("Phase", "Purpose", "Evidence branch"): "Four-phase workflow for baseline capture and branch-isolated remediation evidence.",
    ("Environment item", "Value", "Why it matters"): "Testing environment and reproducibility configuration.",
    (
        "Category",
        "Representative endpoints",
        "Evidence source",
        "Reviewer relevance",
    ): "API endpoint coverage used for side-by-side security and performance evidence.",
    (
        "Rule or area",
        "File",
        "Before",
        "After",
        "Status",
    ): "SonarQube code-quality remediation evidence by rule, file, and fix.",
    (
        "Scan",
        "Severity",
        "Before -> After",
        "Vulnerability class",
        "Fix applied",
    ): "OWASP ZAP before-and-after security evidence.",
    (
        "Profile",
        "Metric",
        "Baseline",
        "After fixes",
        "Change",
        "Status",
    ): "JMeter before-and-after performance profile comparison.",
    (
        "Example",
        "Before branch",
        "Before code",
        "After branch",
        "After code",
        "Reason",
    ): "Selected before-and-after code evidence linked to reviewer comments.",
    (
        "Prompt component",
        "Content used in this study",
        "Purpose",
    ): "Prompt-template traceability used in remediation runs.",
    (
        "Fix class",
        "Evidence branch",
        "LLM rounds",
        "Human intervention",
        "Acceptance evidence",
    ): "Human-effort traceability for accepted remediation fixes.",
    (
        "Seed item",
        "Repo-backed value",
        "Purpose in the study",
    ): "Repo-seeded test-data configuration.",
    (
        "Entity",
        "Repo-backed seeded or generated data",
        "How it is produced",
        "API behavior tested",
    ): "Seeded entity coverage for the API behavior under test.",
    (
        "AccountCode",
        "AccountName",
        "AccountType",
        "IsActive",
        "Evidence note",
    ): "Representative ChartOfAccounts records generated by the seed script.",
    (
        "Username or user type",
        "Email/source",
        "Role coverage",
        "UserId",
        "Password evidence",
    ): "Representative user and role records used for authenticated API checks.",
    (
        "ReferenceNo pattern",
        "Description pattern",
        "Status",
        "Entry date",
        "Evidence note",
    ): "Representative journal-entry records generated for posting and report-performance paths.",
    (
        "PeriodId",
        "StartDate",
        "EndDate",
        "IsClosed",
        "Evidence note",
    ): "Accounting-period record used by period-sensitive report tests.",
    (
        "Report type",
        "Endpoint",
        "Input data",
        "Generated result",
    ): "Report outputs generated from seeded posted journal entries.",
    (
        "Evidence area",
        "Evidence area",
        "Repo-backed value or pattern",
        "Repo-backed value or pattern",
        "Reviewer relevance",
        "Reviewer relevance",
    ): "Report-item and audit-log evidence derived from seeded workflows.",
    (
        "Evaluation area",
        "Measure",
        "Acceptance target",
        "Result",
    ): "Evaluation criteria used to judge full-report remediation success.",
    (
        "Metric",
        "Baseline",
        "After fixes",
        "Interpretation",
    ): "SonarQube before-and-after quality metrics.",
    (
        "Area",
        "Before",
        "After",
        "Effect",
    ): "Maintainability-focused code-quality comparison.",
    (
        "Tool",
        "Baseline evidence",
        "After-fix evidence",
        "Closure status",
    ): "Security and quality-gate closure matrix.",
    (
        "Endpoint",
        "Profile metric",
        "Baseline",
        "After fixes",
        "Main remediation",
    ): "Performance hotspot comparison for reviewer-visible report endpoints.",
    (
        "Track",
        "Branch or source",
        "Commit",
    ): "GPT-5.4 and GPT-5.5 benchmark branch provenance.",
    (
        "Model",
        "Quality gate",
        "Coverage",
        "Code smells",
        "Bugs",
        "Vulnerabilities",
        "NCLOC",
    ): "SonarQube outcome comparison for GPT-5.4 and GPT-5.5.",
    (
        "Scan",
        "Before fixes",
        "GPT-5.4 normalized",
        "GPT-5.5 final",
    ): "OWASP ZAP outcome comparison for GPT-5.4 and GPT-5.5.",
    (
        "Profile",
        "Metric",
        "Before fixes",
        "GPT-5.4 normalized",
        "GPT-5.5 final",
    ): "Apache JMeter outcome comparison for GPT-5.4 and GPT-5.5.",
    (
        "Run",
        "Soak drift",
        "Spike drift",
        "Gate result",
    ): "Apache JMeter drift-gate comparison.",
    (
        "Track",
        "GPT-5.4 source/test patch",
        "GPT-5.5 source/test patch",
        "Verification evidence",
    ): "Patch size, tests, and process evidence for GPT-5.4 and GPT-5.5.",
    (
        "Measure",
        "GPT-5.4 v2",
        "GPT-5.5 v2",
        "Interpretation",
    ): "New-API v2 SonarQube and OWASP ZAP results with JMeter comparison readiness.",
}

SPLIT_HEADING_PREFIXES = {
    "3.3 Model and Tool Selection": "This research employs",
    "3.4 Implementation of ChatGPT-Guided Improvements": "After baseline testing",
    "3.5 Testing Phases": "The same financial accounting",
    "4.2 Security Evaluation Plan": "The security evaluation plan",
    "4.3 Performance Evaluation Plan": "Performance testing",
    "4.4 Code Quality Evaluation Plan": "Code quality is assessed",
    "4.5 Comparative Analysis": "Results from each testing",
}

ACRONYMS = [
    ("AI", "Artificial Intelligence"),
    ("API", "Application Programming Interface"),
    ("ARM", "Azure Resource Manager"),
    ("ASP.NET", "Active Server Pages .NET"),
    ("BAL", "Business Access Layer"),
    ("CI/CD", "Continuous Integration / Continuous Delivery"),
    ("COEP", "Cross-Origin Embedder Policy"),
    ("COOP", "Cross-Origin Opener Policy"),
    ("CORP", "Cross-Origin Resource Policy"),
    ("CORS", "Cross-Origin Resource Sharing"),
    ("CPU", "Central Processing Unit"),
    ("CRUD", "Create, Read, Update, Delete"),
    ("CSRF", "Cross-Site Request Forgery"),
    ("CSP", "Content Security Policy"),
    ("CWE", "Common Weakness Enumeration"),
    ("DAST", "Dynamic Application Security Testing"),
    ("DTO", "Data Transfer Object"),
    ("EF", "Entity Framework"),
    ("GPT", "Generative Pre-trained Transformer"),
    ("GUID", "Globally Unique Identifier"),
    ("HTTP", "Hypertext Transfer Protocol"),
    ("IDE", "Integrated Development Environment"),
    ("IEEE", "Institute of Electrical and Electronics Engineers"),
    ("JSON", "JavaScript Object Notation"),
    ("JWT", "JSON Web Token"),
    ("LINQ", "Language Integrated Query"),
    ("LLM", "Large Language Model"),
    ("ML", "Machine Learning"),
    ("MVC", "Model-View-Controller"),
    ("NCLOC", "Non-Comment Lines of Code"),
    ("NER", "Named Entity Recognition"),
    ("NLP", "Natural Language Processing"),
    ("OWASP", "Open Worldwide Application Security Project"),
    ("p50", "50th-percentile latency (median)"),
    ("p95", "95th-percentile latency"),
    ("p99", "99th-percentile latency"),
    ("RBAC", "Role-Based Access Control"),
    ("REST", "Representational State Transfer"),
    ("SDK", "Software Development Kit"),
    ("SE", "Software Engineering"),
    ("SLA", "Service-Level Agreement"),
    ("SLR", "Systematic Literature Review"),
    ("SQL", "Structured Query Language"),
    ("SZZ", "Sliwerski-Zimmermann-Zeller algorithm"),
    ("TSV", "Tab-Separated Values"),
    ("UI", "User Interface"),
    ("URL", "Uniform Resource Locator"),
    ("VU", "Virtual User"),
    ("XSS", "Cross-Site Scripting"),
    ("ZAP", "Zed Attack Proxy"),
]

# Each tuple is: leading text, italicized publication/container, trailing text,
# and an optional permanent URL. Entries are alphabetized by first author.
REFERENCE_ENTRIES = [
    (
        "Chen, E., Huang, R., Chen, H.-S., Tseng, Y.-H., & Li, L.-Y. (2023). ",
        "GPTutor: A ChatGPT-powered programming tool for code explanation",
        " [Preprint]. arXiv. ",
        "https://doi.org/10.48550/arXiv.2305.01863",
    ),
    (
        "Fajkovic, E., & Rundberg, E. (2023). ",
        "The impact of AI-generated code on web development: A comparative study of ChatGPT and GitHub Copilot",
        " [Bachelor's thesis, Blekinge Institute of Technology]. DiVA. ",
        "https://www.diva-portal.org/smash/record.jsf?pid=diva2:1769082",
    ),
    (
        "Flores, C. P., Jr., & Monreal, R. N. (2024). Evaluation of common security vulnerabilities of state universities and colleges websites based on OWASP. ",
        "Journal of Electrical Systems, 20",
        "(5s), 1396-1404. ",
        "https://doi.org/10.52783/jes.2471",
    ),
    (
        "Hou, X., Zhao, Y., Liu, Y., Yang, Z., Wang, K., Li, L., Luo, X., Lo, D., Grundy, J., & Wang, H. (2024). Large language models for software engineering: A systematic literature review. ",
        "ACM Transactions on Software Engineering and Methodology, 33",
        "(8), Article 220, 1-79. ",
        "https://doi.org/10.1145/3695988",
    ),
    (
        "Khoury, R., Avila, A. R., Brunelle, J., & Camara, B. M. (2023). How secure is code generated by ChatGPT? In ",
        "2023 IEEE International Conference on Systems, Man, and Cybernetics (SMC)",
        " (pp. 2445-2451). IEEE. ",
        "https://doi.org/10.1109/SMC53992.2023.10394237",
    ),
    (
        "Lenarduzzi, V., Lomio, F., Huttunen, H., & Taibi, D. (2020). Are SonarQube rules inducing bugs? In ",
        "2020 IEEE 27th International Conference on Software Analysis, Evolution and Reengineering (SANER)",
        " (pp. 501-511). IEEE. ",
        "https://doi.org/10.1109/SANER48275.2020.9054821",
    ),
    (
        "Mousavi, Z., Islam, C., Moore, K., Abuadbba, A., & Babar, M. A. (2024). An investigation into misuse of Java security APIs by large language models. In ",
        "Proceedings of the 19th ACM Asia Conference on Computer and Communications Security",
        " (pp. 1299-1315). ACM. ",
        "https://doi.org/10.1145/3634737.3661134",
    ),
    (
        "Özpolat, Z., Yıldırım, Ö., & Karabatak, M. (2023). Artificial intelligence-based tools in software development processes: Application of ChatGPT. ",
        "European Journal of Technic, 13",
        "(2). ",
        "https://doi.org/10.36222/ejt.1330631",
    ),
    (
        "Pearce, H., Ahmad, B., Tan, B., Dolan-Gavitt, B., & Karri, R. (2022). Asleep at the keyboard? Assessing the security of GitHub Copilot's code contributions. In ",
        "2022 IEEE Symposium on Security and Privacy (SP)",
        " (pp. 754-768). IEEE. ",
        "https://doi.org/10.1109/SP46214.2022.9833571",
    ),
    (
        "Peng, S., Kalliamvakou, E., Cihon, P., & Demirer, M. (2023). ",
        "The impact of AI on developer productivity: Evidence from GitHub Copilot",
        " [Preprint]. arXiv. ",
        "https://doi.org/10.48550/arXiv.2302.06590",
    ),
    (
        "Ságodi, Z., Siket, I., & Ferenc, R. (2024). Methodology for code synthesis evaluation of LLMs presented by a case study of ChatGPT and Copilot. ",
        "IEEE Access, 12",
        ", 72303-72316. ",
        "https://doi.org/10.1109/ACCESS.2024.3403858",
    ),
    (
        "Sandoval, G., Pearce, H., Nys, T., Karri, R., Garg, S., & Dolan-Gavitt, B. (2023). Lost at C: A user study on the security implications of large language model code assistants. In ",
        "32nd USENIX Security Symposium (USENIX Security 23)",
        " (pp. 2205-2222). USENIX Association. ",
        "https://www.usenix.org/conference/usenixsecurity23/presentation/sandoval",
    ),
    (
        "Szabó, Z., & Bilicki, V. (2023). A new approach to web application security: Utilizing GPT language models for source code inspection. ",
        "Future Internet, 15",
        "(10), Article 326. ",
        "https://doi.org/10.3390/fi15100326",
    ),
    (
        "Yetiştiren, B., Özsoy, I., Ayerdem, M., & Tüzün, E. (2023). ",
        "Evaluating the code quality of AI-assisted code generation tools: An empirical study on GitHub Copilot, Amazon CodeWhisperer, and ChatGPT",
        " [Preprint]. arXiv. ",
        "https://doi.org/10.48550/arXiv.2304.10778",
    ),
    (
        "Zhang, N., Zou, Y., Xia, X., Huang, Q., Lo, D., & Li, S. (2023). Web APIs: Features, issues, and expectations - A large-scale empirical study of Web APIs from two publicly accessible registries using Stack Overflow and a user survey. ",
        "IEEE Transactions on Software Engineering, 49",
        "(2), 498-528. ",
        "https://doi.org/10.1109/TSE.2022.3154769",
    ),
]


def normalized_text(paragraph: Paragraph) -> str:
    return " ".join(paragraph.text.split())


def iter_blocks(doc: Document) -> list[Paragraph | Table]:
    blocks: list[Paragraph | Table] = []
    for child in doc.element.body.iterchildren():
        if child.tag.endswith("}p"):
            blocks.append(Paragraph(child, doc))
        elif child.tag.endswith("}tbl"):
            blocks.append(Table(child, doc))
    return blocks


def insert_paragraph_before(paragraph: Paragraph, text: str = "") -> Paragraph:
    new_p = OxmlElement("w:p")
    paragraph._p.addprevious(new_p)
    new_para = Paragraph(new_p, paragraph._parent)
    if text:
        new_para.add_run(text)
    return new_para


def insert_paragraph_after(paragraph: Paragraph, text: str = "") -> Paragraph:
    new_p = OxmlElement("w:p")
    paragraph._p.addnext(new_p)
    new_para = Paragraph(new_p, paragraph._parent)
    if text:
        new_para.add_run(text)
    return new_para


def insert_caption_before_table(table: Table) -> Paragraph:
    new_p = OxmlElement("w:p")
    table._tbl.addprevious(new_p)
    return Paragraph(new_p, table._parent)


def remove_paragraph(paragraph: Paragraph) -> None:
    parent = paragraph._element.getparent()
    if parent is not None:
        parent.remove(paragraph._element)


def set_paragraph_text(paragraph: Paragraph, text: str) -> None:
    paragraph.clear()
    paragraph.add_run(text)


def configure_caption_style(doc: Document) -> None:
    style = doc.styles["Caption"]
    style.font.name = "Times New Roman"
    style.font.size = Pt(12)
    style.font.bold = False
    style.font.italic = False
    style.paragraph_format.line_spacing = 2.0
    style.paragraph_format.first_line_indent = Inches(0)
    style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
    fonts = style.element.get_or_add_rPr().get_or_add_rFonts()
    fonts.set(qn("w:eastAsia"), "Times New Roman")
    fonts.set(qn("w:cs"), "Times New Roman")


def configure_heading_styles(doc: Document) -> None:
    for style_name, size in HEADING_STYLE_SIZES.items():
        style = doc.styles[style_name]
        style.font.name = "Times New Roman"
        style.font.size = Pt(size)
        style.font.bold = True
        style.font.italic = False
        style.font.color.rgb = RGBColor(0, 0, 0)
        style.paragraph_format.line_spacing = 2.0
        style.paragraph_format.first_line_indent = Inches(0)
        fonts = style.element.get_or_add_rPr().get_or_add_rFonts()
        fonts.set(qn("w:eastAsia"), "Times New Roman")
        fonts.set(qn("w:cs"), "Times New Roman")


def normalize_numbering_fonts(doc: Document) -> None:
    numbering = doc.part.numbering_part.element
    for abstract in numbering:
        if abstract.tag != qn("w:abstractNum"):
            continue
        for level in abstract:
            if level.tag != qn("w:lvl"):
                continue
            number_format = level.find(qn("w:numFmt"))
            label = level.find(qn("w:lvlText"))
            if number_format is not None and number_format.get(qn("w:val")) == "bullet" and label is not None:
                glyph = label.get(qn("w:val"))
                label.set(qn("w:val"), {"\uf0b7": "•", "\uf0a7": "▪", "o": "○"}.get(glyph, glyph))
            run_properties = level.find(qn("w:rPr"))
            if run_properties is None:
                run_properties = OxmlElement("w:rPr")
                level.append(run_properties)
            fonts = run_properties.find(qn("w:rFonts"))
            if fonts is None:
                fonts = OxmlElement("w:rFonts")
                run_properties.insert(0, fonts)
            for attribute in ("ascii", "hAnsi", "cs", "eastAsia"):
                fonts.set(qn(f"w:{attribute}"), "Times New Roman")


def enforce_document_typography(doc: Document) -> None:
    """Keep prose and generated lists stable across every document refresh."""
    paragraphs = list(doc.paragraphs)
    toc_index = next(
        i for i, paragraph in enumerate(paragraphs)
        if normalized_text(paragraph) == "Table of Contents"
    )
    body_index = next(
        i for i, paragraph in enumerate(paragraphs)
        if normalized_text(paragraph) == "Chapter 1 - Introduction"
        and paragraph.style.name == "Heading 1"
    )
    appendix_index = next(
        i for i, paragraph in enumerate(paragraphs)
        if normalized_text(paragraph) == "APPENDICES"
        and paragraph.style.name == "Heading 1"
    )
    references_index = next(
        (
            i for i, paragraph in enumerate(paragraphs)
            if normalized_text(paragraph) in {"REFERENCES", "References"}
            and paragraph.style.name == "Heading 1"
        ),
        appendix_index,
    )

    normal = doc.styles["Normal"]
    normal.font.name = "Times New Roman"
    normal.font.size = Pt(12)
    normal.paragraph_format.line_spacing = 2.0
    normal.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    normal.paragraph_format.first_line_indent = Inches(0.5)
    for style_name in ("List Paragraph", "Appendix Bullet"):
        if style_name not in doc.styles:
            continue
        style = doc.styles[style_name]
        style.font.name = "Times New Roman"
        style.font.size = Pt(12)
        style.paragraph_format.line_spacing = 2.0
        style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    if "Appendix Code" in doc.styles:
        code_style = doc.styles["Appendix Code"]
        code_style.font.name = "Courier New"
        code_style.font.size = Pt(9.5)
        code_style.paragraph_format.line_spacing = 1.0
        code_style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.LEFT

    normalize_numbering_fonts(doc)
    configure_caption_style(doc)
    configure_heading_styles(doc)
    for index, paragraph in enumerate(paragraphs):
        text = normalized_text(paragraph)
        style_name = paragraph.style.name
        if style_name == "Appendix Code":
            font_name, font_size = "Courier New", 9.5
            paragraph.paragraph_format.line_spacing = 1.0
            paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
        elif style_name in HEADING_STYLE_SIZES:
            font_name, font_size = "Times New Roman", HEADING_STYLE_SIZES[style_name]
            paragraph.paragraph_format.line_spacing = 2.0
            paragraph.paragraph_format.first_line_indent = Inches(0)
        elif style_name == "Caption":
            font_name, font_size = "Times New Roman", 12
            paragraph.paragraph_format.line_spacing = 2.0
            paragraph.paragraph_format.first_line_indent = Inches(0)
            paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        elif index < toc_index:
            # Preserve the cover's deliberate title sizes and positioning.
            font_name, font_size = "Times New Roman", None
            paragraph.paragraph_format.first_line_indent = Inches(0)
        elif index < body_index:
            title = text in {"Table of Contents", "Table of Figures", "List of Tables"}
            font_name, font_size = "Times New Roman", 14 if title else 12
            paragraph.paragraph_format.line_spacing = 2.0
            paragraph.paragraph_format.first_line_indent = Inches(0)
            paragraph.alignment = (
                WD_ALIGN_PARAGRAPH.CENTER if title else WD_ALIGN_PARAGRAPH.LEFT
            )
        elif index < references_index or index >= appendix_index:
            font_name, font_size = "Times New Roman", 12
            if text and style_name in {"Normal", "List Paragraph", "Appendix Bullet"}:
                paragraph.paragraph_format.line_spacing = 2.0
                paragraph.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
                if style_name == "Normal":
                    paragraph.paragraph_format.first_line_indent = Inches(0.5)
                if style_name == "Appendix Bullet" or text.startswith(
                    ("Classification:", "Source:", "Source.", "Verification:")
                ):
                    paragraph.paragraph_format.first_line_indent = Inches(0)
                    paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
        else:
            font_name, font_size = "Times New Roman", 12
            if text:
                paragraph.paragraph_format.line_spacing = 2.0
                paragraph.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
                paragraph.paragraph_format.left_indent = Inches(0.5)
                paragraph.paragraph_format.first_line_indent = Inches(-0.5)

        if body_index <= index < references_index:
            if text in EXAMPLE_LABELS:
                paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
                paragraph.paragraph_format.left_indent = Inches(0.5)
                paragraph.paragraph_format.first_line_indent = Inches(0)
                paragraph.paragraph_format.space_before = Pt(0)
                paragraph.paragraph_format.space_after = Pt(0)
                paragraph.paragraph_format.keep_with_next = True
            elif text.startswith("Source-code evidence "):
                paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
                paragraph.paragraph_format.left_indent = Inches(0)
                paragraph.paragraph_format.first_line_indent = Inches(0)
                paragraph.paragraph_format.keep_with_next = True
            elif text.startswith(EXAMPLE_DETAIL_PREFIXES):
                paragraph.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
                paragraph.paragraph_format.left_indent = Inches(0.5)
                paragraph.paragraph_format.first_line_indent = Inches(0)

        if paragraph._p.xpath("./w:pPr/w:numPr"):
            # The numbering definition supplies its own hanging indent.
            paragraph.paragraph_format.first_line_indent = None
            paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
            if text.startswith("Phase ") and len(text) < 80:
                paragraph.paragraph_format.keep_with_next = True

        for element in paragraph._p.xpath(".//w:r"):
            run = Run(element, paragraph)
            if not run.text:
                continue
            chosen_font = (
                "Courier New"
                if font_name == "Courier New" or run.font.name == "Courier New"
                else "Times New Roman"
            )
            run.font.name = chosen_font
            if font_size is not None:
                run.font.size = Pt(font_size)
            fonts = element.get_or_add_rPr().get_or_add_rFonts()
            fonts.set(qn("w:eastAsia"), chosen_font)
            fonts.set(qn("w:cs"), chosen_font)

    for section in doc.sections:
        for part in (section.header, section.footer):
            for paragraph in part.paragraphs:
                for run in paragraph.runs:
                    run.font.name = "Times New Roman"
                    run.font.size = Pt(12)


def normalize_heading_runs(doc: Document) -> None:
    for paragraph in doc.paragraphs:
        size = HEADING_STYLE_SIZES.get(paragraph.style.name)
        if size is None:
            continue
        for run in paragraph.runs:
            run.font.name = "Times New Roman"
            run.font.size = Pt(size)
            run.bold = True
            run.italic = False
            run.underline = False
            run.font.color.rgb = RGBColor(0, 0, 0)


def add_page_break_after(paragraph: Paragraph) -> Paragraph:
    breaker = insert_paragraph_after(paragraph)
    breaker.add_run().add_break(WD_BREAK.PAGE)
    return breaker


def add_complex_field(paragraph: Paragraph, instruction: str, placeholder: str) -> None:
    paragraph.clear()

    begin_run = OxmlElement("w:r")
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    begin.set(qn("w:dirty"), "true")
    begin_run.append(begin)
    paragraph._p.append(begin_run)

    instr_run = OxmlElement("w:r")
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = f" {instruction} "
    instr_run.append(instr)
    paragraph._p.append(instr_run)

    separate_run = OxmlElement("w:r")
    separate = OxmlElement("w:fldChar")
    separate.set(qn("w:fldCharType"), "separate")
    separate_run.append(separate)
    paragraph._p.append(separate_run)

    result_run = OxmlElement("w:r")
    text = OxmlElement("w:t")
    text.text = placeholder
    result_run.append(text)
    paragraph._p.append(result_run)

    end_run = OxmlElement("w:r")
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    end_run.append(end)
    paragraph._p.append(end_run)


def add_tc_field(paragraph: Paragraph, entry: str, flag: str) -> None:
    begin_run = OxmlElement("w:r")
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    begin_run.append(begin)
    paragraph._p.append(begin_run)

    instr_run = OxmlElement("w:r")
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    escaped = entry.replace('"', "'")
    instr.text = f' TC "{escaped}" \\f {flag} '
    instr_run.append(instr)
    paragraph._p.append(instr_run)

    end_run = OxmlElement("w:r")
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    end_run.append(end)
    paragraph._p.append(end_run)


def enable_field_update_on_open(doc: Document) -> None:
    settings = doc.settings.element
    update_fields = settings.find(qn("w:updateFields"))
    if update_fields is None:
        update_fields = OxmlElement("w:updateFields")
    else:
        settings.remove(update_fields)
    update_fields.set(qn("w:val"), "true")

    compat = settings.find(qn("w:compat"))
    if compat is not None:
        compat.addprevious(update_fields)
    else:
        settings.append(update_fields)


def style_front_matter_title(paragraph: Paragraph, text: str) -> None:
    set_paragraph_text(paragraph, text)
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    paragraph.paragraph_format.space_before = Pt(18)
    paragraph.paragraph_format.space_after = Pt(12)
    paragraph.paragraph_format.line_spacing = 2.0
    paragraph.paragraph_format.first_line_indent = Inches(0)
    for run in paragraph.runs:
        run.bold = True
        run.font.name = "Times New Roman"
        run.font.size = Pt(14)


def list_key(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", text.lower())


def collect_toc_entries(doc: Document) -> list[dict[str, str | int]]:
    entries: list[dict[str, str | int]] = []
    for paragraph in doc.paragraphs:
        text = normalized_text(paragraph)
        if not text or text in {"Table of Contents", "Table of Figures", "List of Tables"}:
            continue
        style_name = paragraph.style.name
        if style_name == "Heading 1":
            if text == "List of Acronyms":
                entries.append({"text": "Table of Figures", "level": 1})
                entries.append({"text": "List of Tables", "level": 1})
            entries.append({"text": text, "level": 1})
        elif style_name == "Heading 2":
            entries.append({"text": text, "level": 2})
        elif style_name == "Heading 3":
            entries.append({"text": text, "level": 3})
    return entries


def collect_caption_entries(doc: Document, prefix: str) -> list[dict[str, str | int]]:
    entries: list[dict[str, str | int]] = []
    for paragraph in doc.paragraphs:
        text = normalized_text(paragraph)
        if text.startswith(prefix):
            entries.append({"text": text, "level": 1})
    return entries


def add_static_list_entry(
    anchor: Paragraph,
    text: str,
    page_number: int | None,
    *,
    level: int = 1,
) -> Paragraph:
    paragraph = insert_paragraph_after(anchor)
    paragraph.paragraph_format.left_indent = Inches(0.25 * max(level - 1, 0))
    paragraph.paragraph_format.space_before = Pt(0)
    paragraph.paragraph_format.space_after = Pt(0)
    paragraph.paragraph_format.line_spacing = 2.0
    paragraph.paragraph_format.first_line_indent = Inches(0)
    paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
    paragraph.paragraph_format.tab_stops.add_tab_stop(
        Inches(6.5),
        WD_TAB_ALIGNMENT.RIGHT,
        WD_TAB_LEADER.DOTS,
    )
    run = paragraph.add_run(text)
    run.font.name = "Times New Roman"
    run.font.size = Pt(12)
    paragraph.add_run("\t")
    page_run = paragraph.add_run(str(page_number) if page_number is not None else "")
    page_run.font.name = "Times New Roman"
    page_run.font.size = Pt(12)
    return paragraph


def add_static_list_page(
    anchor: Paragraph,
    title: str,
    entries: list[dict[str, str | int]],
    page_numbers: dict[str, int] | None,
    *,
    page_break_before: bool = False,
) -> Paragraph:
    title_para = insert_paragraph_after(anchor)
    style_front_matter_title(title_para, title)
    title_para.paragraph_format.page_break_before = page_break_before
    current = title_para
    for entry in entries:
        text = str(entry["text"])
        current = add_static_list_entry(
            current,
            text,
            page_numbers.get(text) if page_numbers else None,
            level=int(entry.get("level", 1)),
        )
    return current


def rebuild_front_matter_lists(
    doc: Document,
    page_numbers: dict[str, int] | None = None,
) -> None:
    paragraphs = doc.paragraphs
    start = next(
        (
            index
            for index, paragraph in enumerate(paragraphs)
            if normalized_text(paragraph) == "Table of Contents"
        ),
        None,
    )
    acronym_matches = [
        paragraph
        for paragraph in paragraphs
        if normalized_text(paragraph) == "List of Acronyms"
        and paragraph.style.name == "Heading 1"
    ]
    acronym = acronym_matches[-1] if acronym_matches else None
    if start is None or acronym is None:
        raise RuntimeError("Could not locate the front-matter TOC/List of Acronyms boundary.")

    for paragraph in paragraphs[start: paragraphs.index(acronym)]:
        remove_paragraph(paragraph)

    toc_entries = collect_toc_entries(doc)
    figure_entries = collect_caption_entries(doc, "Figure ")
    table_entries = collect_caption_entries(doc, "Table ")

    anchor = insert_paragraph_before(acronym)
    # This empty anchor keeps insertion order stable and is removed after the
    # three generated front-matter pages have been inserted.
    current = add_static_list_page(
        anchor,
        "Table of Contents",
        toc_entries,
        page_numbers,
        page_break_before=False,
    )
    current = add_static_list_page(
        current,
        "Table of Figures",
        figure_entries,
        page_numbers,
        page_break_before=True,
    )
    add_static_list_page(
        current,
        "List of Tables",
        table_entries,
        page_numbers,
        page_break_before=True,
    )
    acronym.paragraph_format.page_break_before = True
    remove_paragraph(anchor)


def split_combined_headings(doc: Document) -> None:
    for paragraph in list(doc.paragraphs):
        text = normalized_text(paragraph)
        for heading, body_start in SPLIT_HEADING_PREFIXES.items():
            marker = f"{heading} {body_start}"
            if text.startswith(marker):
                body = text[len(heading):].strip()
                set_paragraph_text(paragraph, heading)
                body_para = insert_paragraph_after(paragraph, body)
                body_para.style = "Normal"
                break


def apply_heading_styles(doc: Document) -> None:
    chapter_one_seen = False
    for paragraph in doc.paragraphs:
        text = normalized_text(paragraph)
        if text == "Chapter 1 - Introduction":
            chapter_one_seen = True
        if not chapter_one_seen:
            continue
        if not text:
            continue
        if text in {"Table of Contents", "Table of Figures", "List of Tables"}:
            continue
        if text.startswith("Chapter overview."):
            paragraph.style = "Normal"
        elif (
            text == "Abstract"
            or re.match(r"^Chapter\s+\d+(\s|-|:)", text)
            or text in {"References", "REFERENCES", "APPENDICES", "List of Acronyms"}
        ):
            paragraph.style = "Heading 1"
        elif text in {
            "Testing Environment and Reproducibility",
            "Selected Source-Code Evidence",
            "Prompt-template evidence added for camera-ready reproducibility.",
            "Human-effort traceability.",
            "Comparison Discussion",
        }:
            paragraph.style = "Heading 2"
        elif re.match(r"^\d+\.\d+\.\d+", text):
            paragraph.style = "Heading 3"
        elif re.match(r"^\d+\.\d+\s", text):
            paragraph.style = "Heading 2"


def find_paragraph(doc: Document, *texts: str) -> Paragraph:
    wanted = set(texts)
    for paragraph in reversed(doc.paragraphs):
        if normalized_text(paragraph) in wanted:
            return paragraph
    raise RuntimeError(f"Could not locate paragraph: {texts}")


def find_paragraph_starting_with(doc: Document, prefix: str) -> Paragraph:
    for paragraph in reversed(doc.paragraphs):
        if normalized_text(paragraph).startswith(prefix):
            return paragraph
    raise RuntimeError(f"Could not locate paragraph starting with: {prefix}")


def paragraph_index(paragraphs: list[Paragraph], target: Paragraph) -> int:
    for index, paragraph in enumerate(paragraphs):
        if paragraph._p is target._p:
            return index
    raise RuntimeError(f"Paragraph is not present in the document: {normalized_text(target)}")


def move_paragraphs_before(paragraphs: list[Paragraph], anchor: Paragraph) -> None:
    for paragraph in paragraphs:
        anchor._p.addprevious(paragraph._p)


def normalize_report_structure(doc: Document) -> None:
    for paragraph in doc.paragraphs:
        text = normalized_text(paragraph)
        match = re.match(r"^(2\.\d+)\.\s+(.+)$", text)
        if match:
            set_paragraph_text(paragraph, f"{match.group(1)} {match.group(2)}")
            paragraph.style = "Heading 2"

    chapter_three_headings = {
        ("What this full report covers", "3.1 Research Design and Workflow"): (
            "3.1 Research Design and Workflow",
            "Heading 2",
        ),
        ("Testing Environment and Reproducibility", "3.1.1 Testing Environment and Reproducibility"): (
            "3.1.1 Testing Environment and Reproducibility",
            "Heading 3",
        ),
        ("Selected Source-Code Evidence", "3.1.2 Selected Source-Code Evidence"): (
            "3.1.2 Selected Source-Code Evidence",
            "Heading 3",
        ),
        (
            "Prompt-template evidence added for camera-ready reproducibility.",
            "3.1.3 Prompt-Template Evidence and Reproducibility",
        ): ("3.1.3 Prompt-Template Evidence and Reproducibility", "Heading 3"),
        ("Human-effort traceability.", "3.1.4 Human-Effort Traceability"): (
            "3.1.4 Human-Effort Traceability",
            "Heading 3",
        ),
    }
    for candidates, (replacement, style_name) in chapter_three_headings.items():
        paragraph = find_paragraph(doc, *candidates)
        set_paragraph_text(paragraph, replacement)
        paragraph.style = style_name

    observed = find_paragraph(doc, "4.1.1 Observed Outcomes from Evaluation Criteria")
    security_heading = find_paragraph(
        doc,
        "4.1.1.1 Security Metrics",
        "4.1.2 Security Metrics",
    )
    performance_heading = find_paragraph(
        doc,
        "4.1.1.2 Performance Metrics",
        "4.1.3 Performance Metrics",
    )
    quality_heading = find_paragraph(
        doc,
        "4.1.1.3 Code Quality Metrics",
        "4.1.4 Code Quality Metrics",
    )
    discussion_heading = find_paragraph(
        doc,
        "Comparison Discussion",
        "4.1.5 Comparison Discussion",
    )

    heading_updates = [
        (observed, "4.1.1 Observed Outcomes from Evaluation Criteria"),
        (security_heading, "4.1.2 Security Metrics"),
        (performance_heading, "4.1.3 Performance Metrics"),
        (quality_heading, "4.1.4 Code Quality Metrics"),
        (discussion_heading, "4.1.5 Comparison Discussion"),
    ]
    for paragraph, text in heading_updates:
        set_paragraph_text(paragraph, text)
        paragraph.style = "Heading 3"

    table_4_2 = find_paragraph_starting_with(doc, "Table 4.2.")
    table_4_2._p.addprevious(observed._p)

    security_block = [
        security_heading,
        find_paragraph_starting_with(doc, "Security comparison units:"),
        find_paragraph_starting_with(doc, "Observed authenticated API scan result:"),
        find_paragraph_starting_with(doc, "Observed ZAP baseline scan result:"),
    ]
    performance_block = [
        performance_heading,
        find_paragraph_starting_with(doc, "Performance comparison units:"),
        find_paragraph_starting_with(doc, "Observed stress-profile result:"),
        find_paragraph_starting_with(doc, "Observed JMeter result:"),
    ]
    quality_block = [
        quality_heading,
        find_paragraph_starting_with(doc, "Code-quality comparison units:"),
        find_paragraph_starting_with(doc, "Observed SonarQube result:"),
    ]
    discussion_block = [
        discussion_heading,
        find_paragraph_starting_with(doc, "The SonarQube result is the cleanest closure case"),
        find_paragraph_starting_with(doc, "The ZAP result shows that the vulnerable surface"),
        find_paragraph_starting_with(doc, "The JMeter results show major p95 reductions"),
    ]
    section_4_2 = find_paragraph(doc, "4.2 Security Evaluation Plan")
    move_paragraphs_before(
        security_block + performance_block + quality_block + discussion_block,
        section_4_2,
    )

    for paragraph in doc.paragraphs:
        text = paragraph.text
        if "(Zhang et al., 2022)" in text:
            set_paragraph_text(paragraph, text.replace("(Zhang et al., 2022)", "(Zhang et al., 2023)"))


def rebuild_acronym_list(doc: Document) -> None:
    heading = find_paragraph(doc, "List of Acronyms")
    chapter_one = find_paragraph(doc, "Chapter 1 - Introduction")
    paragraphs = doc.paragraphs
    start = paragraph_index(paragraphs, heading)
    end = paragraph_index(paragraphs, chapter_one)
    for paragraph in paragraphs[start + 1 : end]:
        remove_paragraph(paragraph)

    current = heading
    for acronym, expansion in ACRONYMS:
        current = insert_paragraph_after(current, f"{acronym} - {expansion}")
        current.style = "Normal"
        current.paragraph_format.space_before = Pt(0)
        current.paragraph_format.space_after = Pt(0)
        current.paragraph_format.line_spacing = 2.0
        current.paragraph_format.first_line_indent = Inches(0)
        current.alignment = WD_ALIGN_PARAGRAPH.LEFT
        for run in current.runs:
            run.font.name = "Times New Roman"
            run.font.size = Pt(12)


def add_hyperlink(paragraph: Paragraph, url: str) -> None:
    relationship_id = paragraph.part.relate_to(url, RT.HYPERLINK, is_external=True)
    hyperlink = OxmlElement("w:hyperlink")
    hyperlink.set(qn("r:id"), relationship_id)
    run = OxmlElement("w:r")
    run_properties = OxmlElement("w:rPr")
    run_style = OxmlElement("w:rStyle")
    run_style.set(qn("w:val"), "Hyperlink")
    run_properties.append(run_style)
    size = OxmlElement("w:sz")
    size.set(qn("w:val"), "24")
    run_properties.append(size)
    complex_size = OxmlElement("w:szCs")
    complex_size.set(qn("w:val"), "24")
    run_properties.append(complex_size)
    run.append(run_properties)
    text = OxmlElement("w:t")
    text.text = url
    run.append(text)
    hyperlink.append(run)
    paragraph._p.append(hyperlink)


def rebuild_references(doc: Document) -> None:
    heading = find_paragraph(doc, "References", "REFERENCES")
    paragraphs = doc.paragraphs
    start = paragraph_index(paragraphs, heading)
    appendix = next(
        (
            paragraph
            for paragraph in paragraphs[start + 1 :]
            if normalized_text(paragraph) == "APPENDICES"
        ),
        None,
    )
    end = paragraph_index(paragraphs, appendix) if appendix is not None else len(paragraphs)
    for paragraph in paragraphs[start + 1 : end]:
        remove_paragraph(paragraph)

    for leading, italicized, trailing, url in REFERENCE_ENTRIES:
        paragraph = insert_paragraph_before(appendix) if appendix is not None else doc.add_paragraph()
        paragraph.style = "Normal"
        paragraph.paragraph_format.left_indent = Inches(0.5)
        paragraph.paragraph_format.first_line_indent = Inches(-0.5)
        paragraph.paragraph_format.space_before = Pt(0)
        paragraph.paragraph_format.space_after = Pt(3)
        paragraph.paragraph_format.line_spacing = 2.0
        paragraph.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        leading_run = paragraph.add_run(leading)
        leading_run.font.name = "Times New Roman"
        leading_run.font.size = Pt(12)
        italic_run = paragraph.add_run(italicized)
        italic_run.italic = True
        italic_run.font.name = "Times New Roman"
        italic_run.font.size = Pt(12)
        trailing_run = paragraph.add_run(trailing)
        trailing_run.font.name = "Times New Roman"
        trailing_run.font.size = Pt(12)
        if url:
            add_hyperlink(paragraph, url)


def table_header(table: Table) -> tuple[str, ...]:
    if not table.rows:
        return ()
    return tuple(" ".join(cell.text.split()) for cell in table.rows[0].cells)


def existing_caption_before(blocks: list[Paragraph | Table], table: Table) -> Paragraph | None:
    try:
        index = blocks.index(table)
    except ValueError:
        return None
    if index > 0 and isinstance(blocks[index - 1], Paragraph):
        text = normalized_text(blocks[index - 1])
        if text.startswith(("Figure", "Table")):
            return blocks[index - 1]
    return None


def chapter_from_heading(text: str) -> int | None:
    match = re.match(r"Chapter\s+(\d+)", text)
    if match:
        return int(match.group(1))
    return None


def set_caption(paragraph: Paragraph, text: str, flag: str) -> None:
    paragraph.style = "Caption"
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    paragraph.paragraph_format.keep_with_next = True
    paragraph.paragraph_format.space_before = Pt(6)
    paragraph.paragraph_format.space_after = Pt(4)
    paragraph.paragraph_format.line_spacing = 2.0
    paragraph.paragraph_format.first_line_indent = Inches(0)
    set_paragraph_text(paragraph, text)
    for run in paragraph.runs:
        run.font.name = "Times New Roman"
        run.font.size = Pt(12)
        run.bold = False
        run.italic = False
    add_tc_field(paragraph, text, flag)


def format_data_table(table: Table) -> None:
    try:
        table.style = "Table Grid"
    except KeyError:
        pass
    table.autofit = True
    if table.rows:
        first_row = table.rows[0]
        tr_pr = first_row._tr.get_or_add_trPr()
        if tr_pr.find(qn("w:tblHeader")) is None:
            tr_pr.append(OxmlElement("w:tblHeader"))
        for cell in first_row.cells:
            tc_pr = cell._tc.get_or_add_tcPr()
            shading = tc_pr.find(qn("w:shd"))
            if shading is None:
                shading = OxmlElement("w:shd")
                tc_pr.append(shading)
            shading.set(qn("w:fill"), "D9EAF7")
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.bold = True
    for row_index, row in enumerate(table.rows):
        for cell in row.cells:
            for paragraph in cell.paragraphs:
                paragraph.paragraph_format.space_before = Pt(0)
                paragraph.paragraph_format.space_after = Pt(0)
                for run in paragraph.runs:
                    run.font.size = Pt(10)
                    run.bold = row_index == 0


def number_table_captions(doc: Document) -> None:
    counters: dict[int, int] = {}
    current_chapter: int | None = None
    blocks = iter_blocks(doc)

    for block in blocks:
        if isinstance(block, Paragraph):
            chapter = chapter_from_heading(normalized_text(block))
            if chapter is not None:
                current_chapter = chapter
            continue

        if current_chapter is None:
            continue

        header = table_header(block)
        title = TABLE_CAPTION_TITLES.get(header)
        if title is None:
            continue

        counters[current_chapter] = counters.get(current_chapter, 0) + 1
        caption_text = f"Table {current_chapter}.{counters[current_chapter]}. {title}"
        caption = existing_caption_before(blocks, block) or insert_caption_before_table(block)
        set_caption(caption, caption_text, "T")
        format_data_table(block)


def number_figure_captions(doc: Document) -> None:
    chapter = 4
    figure_index = 0
    blocks = iter_blocks(doc)
    for index, block in enumerate(blocks):
        if not isinstance(block, Paragraph):
            continue
        text = normalized_text(block)
        previous_is_image = (
            index > 0
            and isinstance(blocks[index - 1], Paragraph)
            and bool(blocks[index - 1]._p.xpath(".//w:drawing"))
        )
        if not text.startswith("Figure 4.") or not previous_is_image:
            continue

        figure_index += 1
        title = text
        while True:
            updated = re.sub(r"^Figure\s+4(?:\.6)?\.\d+\.?\s*", "", title).strip()
            if updated == title:
                break
            title = updated
        caption_text = f"Figure {chapter}.{figure_index}. {title}"
        set_caption(block, caption_text, "F")


def export_pdf(docx_path: Path) -> Path:
    if not SOFFICE.exists():
        raise RuntimeError(f"LibreOffice not found at {SOFFICE}")
    with tempfile.TemporaryDirectory(
        prefix=f"lo-profile-{docx_path.stem}-",
        ignore_cleanup_errors=True,
    ) as profile_name:
        profile = Path(profile_name)
        subprocess.run(
            [
                str(SOFFICE),
                f"-env:UserInstallation=file:///{profile.resolve().as_posix()}",
                "--headless",
                "--convert-to",
                "pdf",
                "--outdir",
                str(docx_path.parent),
                str(docx_path),
            ],
            check=True,
            cwd=ROOT,
        )
    return docx_path.with_suffix(".pdf")


def all_generated_list_entries(doc: Document) -> list[dict[str, str | int]]:
    return (
        collect_toc_entries(doc)
        + collect_caption_entries(doc, "Figure ")
        + collect_caption_entries(doc, "Table ")
    )


def extract_pdf_page_keys(pdf_path: Path) -> list[str]:
    from pypdf import PdfReader

    reader = PdfReader(str(pdf_path))
    page_keys: list[str] = []
    for page in reader.pages:
        page_text = page.extract_text() or ""
        page_keys.append(list_key(page_text))
    return page_keys


def matching_rendered_pages(page_keys: list[str], text: str) -> list[int]:
    key = list_key(text)
    if not key:
        return []

    matches: list[int] = []
    for length in (110, 90, 70, 50, 35, 25):
        needle = key[: min(length, len(key))]
        if not needle:
            continue
        matches = [index + 1 for index, page_key in enumerate(page_keys) if needle in page_key]
        if matches:
            break
    return matches


def find_rendered_page(
    page_keys: list[str],
    text: str,
    body_start_page: int,
) -> int | None:
    matches = matching_rendered_pages(page_keys, text)

    if not matches:
        return None
    if text == "Abstract":
        return min(matches)
    if text in {"Table of Figures", "List of Tables", "List of Acronyms"}:
        front_matter_matches = [page for page in matches if page < body_start_page]
        return max(front_matter_matches) if front_matter_matches else min(matches)

    body_matches = [page for page in matches if page >= body_start_page]
    return min(body_matches) if body_matches else max(matches)


def rendered_page_numbers(pdf_path: Path, doc: Document) -> dict[str, int]:
    page_keys = extract_pdf_page_keys(pdf_path)
    chapter_one_matches = matching_rendered_pages(page_keys, "Chapter 1 - Introduction")
    if not chapter_one_matches:
        raise RuntimeError("Could not locate Chapter 1 in the rendered PDF.")
    body_start_page = max(chapter_one_matches)
    page_numbers: dict[str, int] = {}
    for entry in all_generated_list_entries(doc):
        text = str(entry["text"])
        page_number = find_rendered_page(page_keys, text, body_start_page)
        if page_number is not None:
            page_numbers[text] = page_number
    return page_numbers


def select_word_page(text: str, pages: list[int]) -> int | None:
    if not pages:
        return None
    if text == "Abstract":
        return min(pages)
    return max(pages)


def word_rendered_page_numbers(docx_path: Path, doc: Document) -> tuple[dict[str, int], int]:
    import pythoncom
    import win32com.client

    entries = [str(entry["text"]) for entry in all_generated_list_entries(doc)]
    occurrences: dict[str, list[int]] = {text: [] for text in entries}
    word = None
    word_doc = None
    page_count = 0
    pythoncom.CoInitialize()
    try:
        word = win32com.client.DispatchEx("Word.Application")
        word.Visible = False
        word.DisplayAlerts = 0
        word_doc = word.Documents.Open(
            str(docx_path.resolve()),
            ConfirmConversions=False,
            ReadOnly=True,
            AddToRecentFiles=False,
            Visible=False,
        )
        word_doc.Repaginate()
        content_end = int(word_doc.Content.End)
        for text in entries:
            search_range = word_doc.Content.Duplicate
            previous_end = -1
            while search_range.Find.Execute(
                FindText=text,
                MatchCase=True,
                MatchWholeWord=False,
                MatchWildcards=False,
                Forward=True,
                Wrap=0,
                Format=False,
            ):
                paragraph_text = " ".join(
                    str(search_range.Paragraphs(1).Range.Text)
                    .replace("\x07", " ")
                    .split()
                )
                if paragraph_text == " ".join(text.split()):
                    occurrences[text].append(int(search_range.Information(3)))
                next_start = int(search_range.End)
                if next_start <= previous_end or next_start >= content_end:
                    break
                previous_end = next_start
                search_range.SetRange(next_start, content_end)
        page_count = int(word_doc.ComputeStatistics(2))
    finally:
        if word_doc is not None:
            try:
                word_doc.Close(False)
            except Exception:
                pass
        if word is not None:
            try:
                word.Quit()
            except Exception:
                pass
        word_doc = None
        word = None
        pythoncom.CoUninitialize()

    page_numbers: dict[str, int] = {}
    for text, pages in occurrences.items():
        page = select_word_page(text, pages)
        if page is not None:
            page_numbers[text] = page
    return page_numbers, page_count


def export_pdf_word(docx_path: Path) -> Path:
    import pythoncom
    import win32com.client

    pdf_path = docx_path.with_suffix(".pdf")
    word = None
    word_doc = None
    pythoncom.CoInitialize()
    try:
        word = win32com.client.DispatchEx("Word.Application")
        word.Visible = False
        word.DisplayAlerts = 0
        word_doc = word.Documents.Open(
            str(docx_path.resolve()),
            ConfirmConversions=False,
            ReadOnly=True,
            AddToRecentFiles=False,
            Visible=False,
        )
        word_doc.Fields.Update()
        word_doc.Repaginate()
        word_doc.ExportAsFixedFormat(str(pdf_path.resolve()), 17)
    finally:
        if word_doc is not None:
            word_doc.Close(False)
        if word is not None:
            word.Quit()
        word_doc = None
        word = None
        pythoncom.CoUninitialize()
    return pdf_path


def format_report(docx_path: Path) -> None:
    if not docx_path.exists():
        return

    doc = Document(docx_path)
    configure_caption_style(doc)
    configure_heading_styles(doc)
    split_combined_headings(doc)
    normalize_report_structure(doc)
    apply_heading_styles(doc)
    normalize_heading_runs(doc)
    number_table_captions(doc)
    number_figure_captions(doc)
    rebuild_acronym_list(doc)
    rebuild_references(doc)
    rebuild_front_matter_lists(doc)
    enforce_document_typography(doc)
    enable_field_update_on_open(doc)
    doc.save(docx_path)

    pdf_path = export_pdf(docx_path)
    page_numbers = rendered_page_numbers(pdf_path, Document(docx_path))
    for _ in range(3):
        doc = Document(docx_path)
        rebuild_front_matter_lists(doc, page_numbers)
        enforce_document_typography(doc)
        doc.save(docx_path)
        pdf_path = export_pdf(docx_path)
        updated_page_numbers = rendered_page_numbers(pdf_path, Document(docx_path))
        if updated_page_numbers == page_numbers:
            break
        page_numbers = updated_page_numbers

    print(docx_path)
    print(docx_path.with_suffix(".pdf"))


def refresh_generated_lists(docx_path: Path) -> None:
    """Refresh TOC/figure/table lists and PDF without rewriting report sections."""
    if not docx_path.exists():
        return

    doc = Document(docx_path)
    configure_caption_style(doc)
    configure_heading_styles(doc)
    normalize_heading_runs(doc)
    rebuild_front_matter_lists(doc)
    enforce_document_typography(doc)
    enable_field_update_on_open(doc)
    doc.save(docx_path)

    pdf_path = export_pdf(docx_path)
    page_numbers = rendered_page_numbers(pdf_path, Document(docx_path))
    for _ in range(3):
        doc = Document(docx_path)
        rebuild_front_matter_lists(doc, page_numbers)
        enforce_document_typography(doc)
        doc.save(docx_path)
        pdf_path = export_pdf(docx_path)
        updated_page_numbers = rendered_page_numbers(pdf_path, Document(docx_path))
        if updated_page_numbers == page_numbers:
            break
        page_numbers = updated_page_numbers

    print(docx_path)
    print(docx_path.with_suffix(".pdf"))


def refresh_generated_lists_word(docx_path: Path, *, export_pdf: bool = True) -> None:
    """Refresh generated lists from Microsoft Word pagination."""
    if not docx_path.exists():
        return

    doc = Document(docx_path)
    configure_caption_style(doc)
    configure_heading_styles(doc)
    normalize_heading_runs(doc)
    enforce_document_typography(doc)
    enable_field_update_on_open(doc)
    doc.save(docx_path)

    page_numbers, page_count = word_rendered_page_numbers(docx_path, Document(docx_path))
    for _ in range(4):
        doc = Document(docx_path)
        rebuild_front_matter_lists(doc, page_numbers)
        enforce_document_typography(doc)
        doc.save(docx_path)
        updated_page_numbers, updated_page_count = word_rendered_page_numbers(
            docx_path, Document(docx_path)
        )
        page_count = updated_page_count
        if updated_page_numbers == page_numbers:
            break
        page_numbers = updated_page_numbers
    else:
        doc = Document(docx_path)
        rebuild_front_matter_lists(doc, page_numbers)
        enforce_document_typography(doc)
        doc.save(docx_path)

    if export_pdf:
        export_pdf_word(docx_path)
    print(docx_path)
    if export_pdf:
        print(docx_path.with_suffix(".pdf"))
    print(f"Microsoft Word pages: {page_count}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Format final-report DOCX files and rebuild their generated lists.")
    parser.add_argument(
        "targets",
        nargs="*",
        type=Path,
        help="DOCX paths to update. Defaults to both final-report deliverables.",
    )
    parser.add_argument(
        "--lists-only",
        action="store_true",
        help="Refresh generated front-matter lists and PDF without structural normalization.",
    )
    parser.add_argument(
        "--word-native",
        action="store_true",
        help="Refresh lists from Microsoft Word pagination and export the matching PDF.",
    )
    parser.add_argument(
        "--no-pdf",
        action="store_true",
        help="Refresh Word-native lists without exporting a PDF.",
    )
    args = parser.parse_args()
    targets = [path.resolve() for path in args.targets] if args.targets else TARGETS
    for target in targets:
        if args.word_native:
            refresh_generated_lists_word(target, export_pdf=not args.no_pdf)
        elif args.lists_only:
            refresh_generated_lists(target)
        else:
            format_report(target)


if __name__ == "__main__":
    main()
